"use client";

import { useCallback, useEffect, useState } from "react";
import { Check, Edit3, Plus, Target, Trash2 } from "lucide-react";
import { EmptyState, ErrorState, LoadingState, PageHeader } from "@/components/page";
import { Button, Card, Input, Progress, Spinner } from "@/components/ui";
import { api } from "@/lib/api";
import type { Goal } from "@/lib/types";
import { formatLongDate, money, normalizeMoneyInput, numberValue, percent } from "@/lib/utils";

export default function GoalsPage() {
  const [goals, setGoals] = useState<Goal[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [formOpen, setFormOpen] = useState(false);
  const [name, setName] = useState("");
  const [target, setTarget] = useState("");
  const [current, setCurrent] = useState("0,00");
  const [deadline, setDeadline] = useState("");
  const [saving, setSaving] = useState(false);
  const load = useCallback(async () => { setLoading(true); setError(null); try { setGoals(await api.goals()); } catch (reason) { setError(reason instanceof Error ? reason.message : "Não foi possível carregar suas metas."); } finally { setLoading(false); } }, []);
  useEffect(() => { void load(); }, [load]);
  const create = async () => { setSaving(true); setError(null); try { const normalizedTarget = normalizeMoneyInput(target); const normalizedCurrent = normalizeMoneyInput(current || "0"); if (!name.trim() || !normalizedTarget || Number(normalizedTarget) <= 0 || normalizedCurrent === null || Number(normalizedCurrent) < 0) throw new Error("Dê um nome e informe valores monetários válidos para a meta."); await api.createGoal({ name: name.trim(), target_amount: normalizedTarget, current_amount: normalizedCurrent, deadline: deadline || null }); setName(""); setTarget(""); setCurrent("0,00"); setDeadline(""); setFormOpen(false); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Não foi possível criar a meta."); } finally { setSaving(false); } };
  const archive = async (goal: Goal) => { if (!window.confirm(`Arquivar a meta “${goal.name}”?`)) return; try { await api.archiveGoal(goal.id); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Não foi possível arquivar a meta."); } };
  return <>
    <PageHeader eyebrow="O que você quer construir?" title="Metas financeiras" description="Transforme um desejo em um próximo passo visível — sem perder o presente de vista." action={<Button onClick={() => setFormOpen((value) => !value)}><Plus size={17} /> Nova meta</Button>} />
    {formOpen && <Card className="mb-6 border-navy/15 bg-[#fbfcfa] p-5 md:p-6"><div className="mb-5"><p className="eyebrow">Uma meta de cada vez</p><h2 className="mt-1 font-display text-2xl tracking-[-0.03em]">Para onde você está indo?</h2></div><div className="grid gap-4 md:grid-cols-4"><div className="md:col-span-2"><label className="label" htmlFor="goal-name">Nome da meta</label><Input id="goal-name" value={name} onChange={(event) => setName(event.target.value)} placeholder="Reserva de emergência" /></div><div><label className="label" htmlFor="goal-target">Valor alvo</label><div className="relative"><span className="absolute left-3 top-3 text-sm text-muted">R$</span><Input id="goal-target" inputMode="decimal" value={target} onChange={(event) => setTarget(event.target.value)} placeholder="10.000,00" className="pl-10" /></div></div><div><label className="label" htmlFor="goal-current">Já guardado</label><div className="relative"><span className="absolute left-3 top-3 text-sm text-muted">R$</span><Input id="goal-current" inputMode="decimal" value={current} onChange={(event) => setCurrent(event.target.value)} className="pl-10" /></div></div><div><label className="label" htmlFor="goal-deadline">Prazo <span className="normal-case tracking-normal text-muted/70">(opcional)</span></label><Input id="goal-deadline" type="date" value={deadline} onChange={(event) => setDeadline(event.target.value)} /></div></div><div className="mt-5 flex flex-col-reverse gap-2 sm:flex-row sm:justify-end"><Button variant="quiet" className="w-full sm:w-auto" onClick={() => setFormOpen(false)}>Cancelar</Button><Button className="w-full sm:w-auto" onClick={() => void create()} disabled={saving}>{saving ? <Spinner /> : <Check size={16} />} Criar meta</Button></div></Card>}
    {loading ? <LoadingState label="Buscando seus planos" /> : error && !goals.length ? <ErrorState message={error} onRetry={() => void load()} /> : !goals.length ? <Card><EmptyState title="Ainda não há uma meta" description="Pode ser uma reserva, uma viagem ou uma compra importante. O nome dá forma ao próximo passo." actionLabel="Criar primeira meta" onAction={() => setFormOpen(true)} /></Card> : <div className="grid gap-4 md:grid-cols-2">{goals.map((goal) => <GoalCard key={goal.id} goal={goal} onArchive={() => void archive(goal)} onUpdated={load} />)}</div>}
    {error && goals.length > 0 && <p className="mt-4 rounded-xl bg-rust/5 px-3 py-2 text-sm text-rust">{error}</p>}
  </>;
}

function GoalCard({ goal, onArchive, onUpdated }: { goal: Goal; onArchive: () => void; onUpdated: () => Promise<void> }) {
  const [editing, setEditing] = useState(false);
  const [currentAmount, setCurrentAmount] = useState(goal.current_amount);
  const [saving, setSaving] = useState(false);
  const [editError, setEditError] = useState<string | null>(null);
  const progress = goal.target_amount ? numberValue(goal.current_amount) / numberValue(goal.target_amount) * 100 : 0;
  const saveProgress = async () => { setSaving(true); setEditError(null); try { const normalized = normalizeMoneyInput(currentAmount); if (normalized === null || Number(normalized) < 0) throw new Error("Informe um valor acumulado válido."); await api.updateGoal(goal.id, { current_amount: normalized }); setEditing(false); await onUpdated(); } catch (reason) { setEditError(reason instanceof Error ? reason.message : "Não foi possível atualizar a meta."); } finally { setSaving(false); } };
  return <Card className={`p-5 md:p-6 ${goal.status === "archived" ? "opacity-65" : ""}`}><div className="flex items-start justify-between"><div className="flex items-center gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-butter/70 text-[#796b1b]"><Target size={19} /></span><div><p className="font-semibold text-ink">{goal.name}</p><p className="mt-0.5 text-xs text-muted">{goal.deadline ? `até ${formatLongDate(goal.deadline)}` : "Sem prazo definido"}</p></div></div>{goal.status !== "archived" && <div className="flex gap-1"><button onClick={() => setEditing((value) => !value)} className="rounded-lg p-2 text-muted hover:bg-paper hover:text-navy" aria-label={`Atualizar progresso de ${goal.name}`}><Edit3 size={16} /></button><button onClick={onArchive} className="rounded-lg p-2 text-muted hover:bg-rust/10 hover:text-rust" aria-label={`Arquivar ${goal.name}`}><Trash2 size={16} /></button></div>}</div><div className="mt-8 flex items-end justify-between"><div><p className="text-xs uppercase tracking-[0.12em] text-muted">Progresso</p><p className="mt-1 font-display text-3xl tracking-[-0.035em]">{money(goal.current_amount)}</p></div><p className="text-sm font-semibold text-moss">{percent(progress)}</p></div><div className="mt-4"><Progress value={progress} tone="navy" /></div><div className="mt-3 flex justify-between text-xs text-muted"><span>de {money(goal.target_amount)}</span><span>{goal.status === "active" ? "Em andamento" : goal.status === "completed" ? "Concluída" : "Arquivada"}</span></div>{editing && <div className="mt-5 border-t border-line pt-4"><label className="label" htmlFor={`goal-progress-${goal.id}`}>Valor acumulado</label><div className="flex gap-2"><div className="relative flex-1"><span className="absolute left-3 top-2.5 text-xs text-muted">R$</span><Input id={`goal-progress-${goal.id}`} inputMode="decimal" value={currentAmount} onChange={(event) => setCurrentAmount(event.target.value)} className="h-9 pl-9" /></div><Button size="small" onClick={() => void saveProgress()} disabled={saving}>{saving ? <Spinner /> : <Check size={14} />} Atualizar</Button></div>{editError && <p role="alert" className="mt-2 text-xs text-rust">{editError}</p>}</div>}</Card>;
}
